### ISSUE TITLE
BGP Error: Bad peer AS

### ISSUE THREAD

**Issue by Xanawatt** [Kioubit/FlapAlerted#4]
When starting up FlapAlerted with `./FlapAlerted -asn 4242422314 -asnPosition 1`
I get an error of `level=ERROR msg="connection encountered an error" remote=[fd0b:4d5d:38d9::1]:55909 error="unexpected message of type '3', expected keepalive"`

When I check bird, I see this error on the session: `BGP Error: Bad peer AS`
I looked through the code and saw reference of your ASN `4242423914` here: https://github.com/Kioubit/FlapAlerted/blob/62f5ed43ef6d2dce7a8c05a9f6a74d4388018de7/bgp/bgp.go#L26

Changing this to my ASN worked, but this should reference the asn value passed in. I don't know enough about go to write a PR for this unfortunately.

**Comment by Kioubit** [comment]
Fixed, thanks! I wouldn't have noticed
