### ISSUE TITLE
Build broken since v3.13.1

### ISSUE THREAD

**Issue by Xanawatt** [Kioubit/FlapAlerted#5]
Went to go update to the latest version (was running FlapAlerted 3.12-4-g65b82ed successfully) and am getting build errors:
```
xanawatt@wireguard03:~/FlapAlerted$ make clean
if [ -d "bin/" ]; then find bin/ -type f -delete ;fi
if [ -d "bin/" ]; then rm -d bin/ ;fi
xanawatt@wireguard03:~/FlapAlerted$ make release
CGO_ENABLED=0 go build -tags= -trimpath -ldflags "-X main.Version=`git describe --tags` -s -w" -o bin/FlapAlerted .
# _/home/xanawatt/FlapAlerted
./main.go:59:7: conf.KeepPathInfoDetectedOnly undefined (type config.UserConfig has no field or method KeepPathInfoDetectedOnly)
./main.go:83:7: conf.BgpPort undefined (type config.UserConfig has no field or method BgpPort)
./main.go:84:10: conf.BgpPort undefined (type config.UserConfig has no field or method BgpPort)
./main.go:85:41: conf.BgpPort undefined (type config.UserConfig has no field or method BgpPort)
make: *** [Makefile:12: release] Error 1
```

Seems this starts at 3.13.1 as I am also getting a build error, but only this line:
```
./main.go:58:7: conf.KeepPathInfoDetectedOnly undefined (type config.UserConfig has no field or method KeepPathInfoDetectedOnly)
```

If this is just a me problem, I can run the docker container just fine. This is just a much simpler deployment imo, so I'd love it to work. From my limited go knowledge, this doesn't make sense as the fields do exist in config/config.go but maybe I'm missing something

**Comment by Kioubit** [comment]
Could you try deleting the existing repository and cloning the git repository from scratch?

**Comment by Xanawatt** [comment]
I was able to get it to build on a different system. Cloning it from scratch does not work on the problematic one. Don't know what happened, but I guess it's alright. Thanks
